### ISSUE TITLE
The file path for the certificate and the CLI are missing after the any deployment on frappe cloud

### ISSUE THREAD

**Issue by omarashrafsarhan** [lavaloon-eg/ksa_compliance#118] opened 2024-09-12 12:29 UTC
After any deployment or update on the instance using frappe cloud, the file paths for the KSA compliance app’s CLI and certificate are reset. This causes errors for users, requiring them to re-download the CLI and re-create the certificate, forcing them to go through the onboarding process again.

**Preconditions** 

- The server must have the certificate and CLI added to the correct file paths.
- The company must be onboarded through ZATCA business settings.

**Repro Steps** 

1. Open ZATCA business settings.
2. Onboard a company.
3. Create a sales invoice for the onboarded company.
4. Perform an update or deployment on the instance.
5. Attempt to create a new sales invoice for the onboarded company.

**Actual results **

1. The user receives an error related to the missing CLI file path, prompting them to download it again.
2. After downloading the CLI, another error related to the missing certificate path is displayed.

**Expected Results**

1. The file paths for the CLI and certificate should be saved in the database.
2. These file paths should persist through any deployment or update without requiring the user to re-download or re-enter information.
3. No errors should be displayed when creating new sales invoices after deployment.
4. 
5.

**Comment by meaziz** [comment] 2024-09-17 07:56
Same happens upon auto update..

**Comment by mhaggag** [comment] 2024-09-29 08:55
Fixed in 0.33.1. Self-hosted instances will migrate files under the site directory. Unfortunately, frappe cloud sites will lose the files prior to running the migration patch, so you'll have to onboard one last time to generate the new files under the site directory.

**Closed by mhaggag** 2024-09-29 08:55 UTC

**Comment by meaziz** [comment] 2024-09-30 09:05
So to confirm our understanding
on FC With each update (migrate) the onboarding steps will need to be followed?

**Comment by mhaggag** [comment] 2024-09-30 10:22
> So to confirm our understanding on FC With each update (migrate) the onboarding steps will need to be followed?

No, just one last time after updating to 0.33.1 (or later). 0.33.1 and later generate ZATCA files and tools (JRE and CLI) under the site directory, which is preserved across updates. The problem is that there's no way to run the migration patch that moves existing files into the site directory on frappe cloud instances because when you update from pre-0.33.1 to 0.33.1 the new code is running in a new container which has already lost the files (which previously were under `sites/`, which we found out was not preserved).
